// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID                   pgtype.UUID
	Name                 string
	IngredientCategoryID pgtype.UUID
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
}

type IngredientCategory struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Recipe struct {
	ID           pgtype.UUID
	Name         string
	Instructions string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type RecipeIngredient struct {
	RecipeIngredientsID int32
	RecipeID            pgtype.UUID
	IngredientID        pgtype.UUID
	Quantity            pgtype.Numeric
	UnitID              int32
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type Unit struct {
	ID          int32
	Name        string
	Description pgtype.Text
}
